// Code generated by sqlgen; DO NOT EDIT.
package com.example.mapper;

import org.apache.ibatis.session.SqlSession;

/** Factory for creating {@code ItemsMapper} instances. */
public class ItemsMapperFactory {

    /**
     * Create a {@code ItemsMapper} for the given database driver.
     * <p>
     * Usage without Spring:
     * <pre>
     * SqlSession session = sqlSessionFactory.openSession();
     * ItemsMapper mapper = ItemsMapperFactory.create(session, "postgresql");
     * </pre>
     *
     * Valid driver names: postgresql, oracle, mysql, sqlserver.
     */
    public static ItemsMapper create(SqlSession session, String driver) {
        switch (driver) {
            case "postgresql" -> { return session.getMapper(ItemsMapperPG.class); }
            case "oracle" -> { return session.getMapper(ItemsMapperOracle.class); }
            case "mysql" -> { return session.getMapper(ItemsMapperMySQL.class); }
            case "sqlserver" -> { return session.getMapper(ItemsMapperMSSQL.class); }
        }
        throw new IllegalArgumentException(
            "Unsupported driver: " + driver + ". Supported: postgresql, oracle, mysql, sqlserver");
    }
}
