// Code generated by sqlgen; DO NOT EDIT.
package com.example.mapper;

import com.example.entity.Item;
import com.example.entity.CatCount;
import com.example.entity.ExistsByName;
import com.example.entity.ItemBrief;

import java.util.List;
import java.math.BigDecimal;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.*;
import org.springframework.context.annotation.Profile;

/** Shared Mapper interface. */
public interface ItemsMapper {

    Item findByID(@Param("id") long id);

    List<Item> findAll();

    List<Item> findByCategory(@Param("category") String category);

    List<Item> listPaged(@Param("page_limit") int page_limit, @Param("page_offset") int page_offset);

    void insertItem(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    long insertItemRows(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    long insertAndReturnID(Item item);

    void updateItem(@Param("name") String name, @Param("price") java.math.BigDecimal price, @Param("id") long id);

    void deleteItem(@Param("id") long id);

    long deleteItemRows(@Param("id") long id);

    void upsertItem(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    void upsertIgnore(@Param("name") String name, @Param("category") String category);

    List<Item> searchByName(@Param("keyword") String keyword);

    List<Item> searchOptional(@Param("keyword") String keyword, @Param("keyword_1") String keyword_1);

    List<Item> countByCategory();

    Item existsByName(@Param("name") String name);

    List<Item> findByFilters(@Param("category") String category, @Param("category_1") String category_1, @Param("min_price") java.math.BigDecimal min_price, @Param("min_price_1") java.math.BigDecimal min_price_1, @Param("is_active") Boolean is_active, @Param("is_active_1") Boolean is_active_1);

    long countAll();

    List<String> listNames(@Param("category") String category);

    List<Item> listBrief(@Param("category") String category);

    Item findWithExtra(@Param("id") long id);
}
