// Code generated by sqlgen; DO NOT EDIT.
package com.example.mapper;

import com.example.entity.Item;
import com.example.entity.CatCount;
import com.example.entity.ExistsByName;
import com.example.entity.ItemBrief;

import java.util.List;
import java.math.BigDecimal;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.*;
import org.springframework.context.annotation.Profile;

@Mapper
@Profile("oracle")
public interface ItemsMapperOracle extends ItemsMapper {

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE id = #{id}")
    Item findByID(@Param("id") long id);

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id")
    List<Item> findAll();

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE category = #{category} ORDER BY id")
    List<Item> findByCategory(@Param("category") String category);

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id OFFSET #{page_limit} ROWS FETCH NEXT #{page_offset} ROWS ONLY")
    List<Item> listPaged(@Param("page_limit") int page_limit, @Param("page_offset") int page_offset);

    @Override
    @Insert("INSERT INTO items (name, category, price, stock) VALUES (#{name}, #{category}, #{price}, #{stock})")
    void insertItem(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    @Override
    @Insert("INSERT INTO items (name, category, price, stock) VALUES (#{name}, #{category}, #{price}, #{stock})")
    long insertItemRows(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    @Override
    @Insert("INSERT INTO items (name, category, price, stock) VALUES (#{name}, #{category}, #{price}, #{stock}) RETURNING id")
    @SelectKey(statement = "SELECT seq_items.NEXTVAL FROM dual",
               keyProperty = "id", before = true, resultType = long.class)
    long insertAndReturnID(Item item);

    @Override
    @Update("UPDATE items SET name = #{name}, price = #{price}, updated_at = SYSDATE WHERE id = #{id}")
    void updateItem(@Param("name") String name, @Param("price") java.math.BigDecimal price, @Param("id") long id);

    @Override
    @Delete("DELETE FROM items WHERE id = #{id}")
    void deleteItem(@Param("id") long id);

    @Override
    @Delete("DELETE FROM items WHERE id = #{id}")
    long deleteItemRows(@Param("id") long id);

    @Override
    @Insert("MERGE INTO items t USING (SELECT (:1, :2, :3, :4) FROM dual) s ON (t.name = s.name) WHEN MATCHED THEN UPDATE SET category = s.category, price = s.price, stock = s.stock WHEN NOT MATCHED THEN INSERT (name, category, price, stock) VALUES (s.name, s.category, s.price, s.stock)")
    void upsertItem(@Param("name") String name, @Param("category") String category, @Param("price") java.math.BigDecimal price, @Param("stock") int stock);

    @Override
    @Insert("BEGIN INSERT INTO items (name, category, price, stock) VALUES (:1, :2, 0, 0); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;")
    void upsertIgnore(@Param("name") String name, @Param("category") String category);

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE LOWER(name) LIKE LOWER(#{keyword}) ORDER BY id")
    List<Item> searchByName(@Param("keyword") String keyword);

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (LOWER(name) LIKE LOWER(#{keyword}) OR #{keyword_1} IS NULL) ORDER BY id")
    List<Item> searchOptional(@Param("keyword") String keyword, @Param("keyword_1") String keyword_1);

    @Override
    @Select("SELECT category, count(*) FROM items GROUP BY category HAVING count(*) >= 0 ORDER BY category")
    List<Item> countByCategory();

    @Override
    @Select("SELECT EXISTS (SELECT 1 FROM items WHERE name = #{name}) FROM dual")
    Item existsByName(@Param("name") String name);

    @Override
    @Select("SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (((category = #{category} OR #{category_1} IS NULL) AND (price >= #{min_price} OR #{min_price_1} IS NULL)) AND (is_active = #{is_active} OR #{is_active_1} IS NULL)) ORDER BY id")
    List<Item> findByFilters(@Param("category") String category, @Param("category_1") String category_1, @Param("min_price") java.math.BigDecimal min_price, @Param("min_price_1") java.math.BigDecimal min_price_1, @Param("is_active") Boolean is_active, @Param("is_active_1") Boolean is_active_1);

    @Override
    @Select("SELECT count(*) FROM items")
    long countAll();

    @Override
    @Select("SELECT name FROM items WHERE category = #{category} ORDER BY name")
    List<String> listNames(@Param("category") String category);

    @Override
    @Select("SELECT id, name, category FROM items WHERE category = #{category} ORDER BY id")
    List<Item> listBrief(@Param("category") String category);

    @Override
    @Select("SELECT id, name, category, price, stock, created_at FROM items WHERE id = #{id}")
    Item findWithExtra(@Param("id") long id);

}
