package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sqlgen-km/sqlgen/engines"
	"github.com/sqlgen-km/sqlgen/meta"
)

// Generate produces Java code (models + mappers + factory) for a parsed DSL file.
func Generate(pf *meta.ParsedFile, pkg PkgCfg, engs []Engine) error {
	stem := meta.FilesStem(pf)

	// {stem} is always appended to model and mapper packages, giving each DSL
	// file (stem) its own namespace. Any leftover "{stem}" placeholder in the
	// config is stripped for backward compatibility.
	modelPkg := strings.TrimSuffix(strings.ReplaceAll(pkg.ModelPackage, "{stem}", ""), ".") + "." + stem
	mapperPkg := strings.TrimSuffix(strings.ReplaceAll(pkg.MapperPackage, "{stem}", ""), ".") + "." + stem

	// Build RunnerSpecs
	specs, models, err := meta.BuildRunnerSpecs([]meta.ParsedFile{*pf}, pf)
	if err != nil {
		return err
	}

	mapperName := mapperShortName(stem)

	// Derive primary model type
	primaryName := strings.TrimSuffix(mapperName, "Mapper")
	modelType := ""
	for _, m := range models {
		if m.Name == primaryName || m.Name == strings.TrimSuffix(primaryName, "s") {
			modelType = m.Name
			break
		}
	}
	if modelType == "" && len(models) > 0 {
		modelType = models[0].Name
	}

	modelDir := filepath.Join(pkg.Out, packageToPath(modelPkg))
	mapperDir := filepath.Join(pkg.Out, packageToPath(mapperPkg))

	// Models
	if err := os.MkdirAll(modelDir, 0755); err != nil {
		return err
	}
	for _, m := range models {
		if err := writeJavaModel(modelDir, m, modelPkg); err != nil {
			return err
		}
	}

	// INSERT RETURNING parameter classes
	for _, spec := range specs {
		if spec.Kind == engines.RunnerReturningScalar && spec.InsertParam != nil && len(spec.InsertParam.Fields) > 0 {
			if err := writeJavaInsertParams(modelDir, modelPkg, spec); err != nil {
				return err
			}
		}
	}

	// Mappers
	if err := os.MkdirAll(mapperDir, 0755); err != nil {
		return err
	}

	if err := writeJavaSharedMapper(mapperDir, mapperName, specs, modelType, modelPkg, mapperPkg); err != nil {
		return err
	}
	for _, eng := range engs {
		enginePkg := mapperPkg
		engineDir := mapperDir
		if pkg.EngineSubPackage {
			enginePkg = mapperPkg + "." + eng.Name()
			engineDir = filepath.Join(mapperDir, eng.Name())
			if err := os.MkdirAll(engineDir, 0755); err != nil {
				return err
			}
		}
		if err := writeJavaEngineMapper(engineDir, enginePkg, mapperName, specs, modelType, modelPkg, mapperPkg, eng); err != nil {
			return err
		}
	}

	// Factory
	return writeJavaFactory(mapperDir, mapperName, engs, mapperPkg, pkg.EngineSubPackage)
}

func writeJavaModel(dir string, model engines.Model, modelPkg string) error {
	path := filepath.Join(dir, model.Name+".java")
	content := javaGenModelFile(model, modelPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaInsertParams(dir, modelPkg string, spec engines.RunnerSpec) error {
	name := spec.Query + "Params"
	path := filepath.Join(dir, name+".java")
	content := javaGenInsertParams(spec, modelPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaSharedMapper(dir, mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string) error {
	path := filepath.Join(dir, mapperName+".java")
	content := javaGenSharedMapperFile(mapperName, specs, modelType, modelPkg, mapperPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaEngineMapper(dir, enginePkg, mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string, eng Engine) error {
	suffix := suffixForJava(eng.Name())
	path := filepath.Join(dir, mapperName+suffix+".java")
	content := javaGenEngineMapperFile(mapperName, specs, modelType, modelPkg, enginePkg, mapperPkg, eng)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaFactory(dir, mapperName string, engs []Engine, mapperPkg string, engineSubPkg bool) error {
	path := filepath.Join(dir, mapperName+"Factory.java")
	content := javaGenFactoryFile(mapperName, engs, mapperPkg, engineSubPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func javaGenModelFile(model engines.Model, modelPkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", modelPkg)

	imports := GenModelImports([]engines.Model{model})
	if imports != "" {
		b.WriteString(imports)
		b.WriteString("\n")
	}

	b.WriteString(GenModel(model))
	return b.String()
}

// javaGenInsertParams generates a mutable POJO parameter class for an INSERT
// RETURNING method. MyBatis injects the generated key via the setter, so the
// class must be mutable (unlike the generated record models).
func javaGenInsertParams(spec engines.RunnerSpec, modelPkg string) string {
	var b strings.Builder
	className := spec.Query + "Params"
	idName := "id"
	if spec.InsertParam != nil && spec.InsertParam.IDName != "" {
		idName = spec.InsertParam.IDName
	}

	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", modelPkg)

	needsTime := false
	needsMath := false
	if spec.InsertParam != nil {
		for _, f := range spec.InsertParam.Fields {
			if goTypeNeedsImport(f.GoType) {
				needsTime = true
			}
			if goTypeNeedsMath(f.GoType) {
				needsMath = true
			}
		}
	}
	if needsMath {
		b.WriteString("import java.math.BigDecimal;\n")
	}
	if needsTime {
		b.WriteString("import java.time.LocalDateTime;\n")
	}
	if needsMath || needsTime {
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "/** INSERT parameters for {@code %s}. */\n", spec.Query)
	fmt.Fprintf(&b, "public class %s {\n", className)

	// Fields (id first for generated key)
	fmt.Fprintf(&b, "    private Long %s;\n", idName)
	if spec.InsertParam != nil {
		for _, f := range spec.InsertParam.Fields {
			fmt.Fprintf(&b, "    private %s %s;\n", go2javaType(f.GoType), f.JavaName)
		}
	}
	b.WriteString("\n")

	// id getter/setter
	idPascal := ToPascal(idName)
	fmt.Fprintf(&b, "    public Long get%s() { return %s; }\n", idPascal, idName)
	fmt.Fprintf(&b, "    public void set%s(Long %s) { this.%s = %s; }\n", idPascal, idName, idName, idName)

	// field getters/setters
	if spec.InsertParam != nil {
		for _, f := range spec.InsertParam.Fields {
			javaType := go2javaType(f.GoType)
			pascal := ToPascal(f.JavaName)
			fmt.Fprintf(&b, "    public %s get%s() { return %s; }\n", javaType, pascal, f.JavaName)
			fmt.Fprintf(&b, "    public void set%s(%s %s) { this.%s = %s; }\n", pascal, javaType, f.JavaName, f.JavaName, f.JavaName)
		}
	}

	b.WriteString("}\n")
	return b.String()
}

func javaGenSharedMapperFile(mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", mapperPkg)

	addModelImports(&b, specs, modelType, modelPkg, mapperPkg)
	b.WriteString(GenMapperImports(specs))
	b.WriteString(GenSharedMapper(mapperName, specs, modelType))
	return b.String()
}

func javaGenEngineMapperFile(mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, enginePkg, mapperPkg string, eng Engine) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", enginePkg)

	addModelImports(&b, specs, modelType, modelPkg, enginePkg)
	if enginePkg != mapperPkg {
		fmt.Fprintf(&b, "import %s.%s;\n", mapperPkg, mapperName)
	}
	b.WriteString(GenMapperImports(specs))

	suffix := suffixForJava(eng.Name())
	b.WriteString(GenEngineMapperHeader(mapperName, eng.Profile(), suffix))
	b.WriteString(eng.GenMapper(mapperName, specs, modelType))
	b.WriteString(GenEngineMapperFooter())
	return b.String()
}

// addModelImports writes import statements for model classes used in method signatures.
func addModelImports(b *strings.Builder, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string) {
	if modelPkg == mapperPkg {
		return // same package, no import needed
	}
	imported := map[string]bool{}
	// Always import the primary model type when different from mapper package
	if modelType != "" && !imported[modelType] {
		imported[modelType] = true
		fmt.Fprintf(b, "import %s.%s;\n", modelPkg, modelType)
	}
	for _, spec := range specs {
		if spec.Kind == engines.RunnerReturningScalar {
			// INSERT RETURNING takes a params class (or reused model) as parameter
			pt := InsertParamType(spec)
			if pt != "" && !imported[pt] {
				imported[pt] = true
				fmt.Fprintf(b, "import %s.%s;\n", modelPkg, pt)
			}
			continue
		}
		if spec.IsScalar {
			continue // scalars don't need model imports
		}
		mt := spec.ModelType
		if mt == "" {
			continue
		}
		if imported[mt] {
			continue
		}
		imported[mt] = true
		fmt.Fprintf(b, "import %s.%s;\n", modelPkg, mt)
	}
	b.WriteString("\n")
}

func javaGenFactoryFile(mapperName string, engs []Engine, mapperPkg string, engineSubPkg bool) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", mapperPkg)
	b.WriteString(GenFactory(mapperName, engs, mapperPkg, engineSubPkg))
	return b.String()
}

func packageToPath(pkg string) string {
	return strings.ReplaceAll(pkg, ".", "/")
}

func lastPackageSeg(pkg string) string {
	idx := strings.LastIndex(pkg, ".")
	if idx < 0 {
		return pkg
	}
	return pkg[idx+1:]
}

func mapperShortName(stem string) string {
	s := strings.ReplaceAll(stem, "-", "_")
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "") + "Mapper"
}

func suffixForJava(engineName string) string {
	switch engineName {
	case "pg":
		return "PG"
	case "mysql":
		return "MySQL"
	case "oracle":
		return "Oracle"
	case "mssql":
		return "MSSQL"
	default:
		return strings.ToUpper(engineName[:1]) + engineName[1:]
	}
}
