package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sqlgen-km/sqlgen/engines"
	"github.com/sqlgen-km/sqlgen/meta"
)

// Generate produces Java code (models + mappers + factory) for a parsed DSL file.
func Generate(pf *meta.ParsedFile, pkg PkgCfg, engs []Engine) error {
	stem := meta.FilesStem(pf)

	// Build RunnerSpecs
	specs, models, err := meta.BuildRunnerSpecs([]meta.ParsedFile{*pf}, pf)
	if err != nil {
		return err
	}

	mapperName := mapperShortName(stem)

	// Derive primary model type
	primaryName := strings.TrimSuffix(mapperName, "Mapper")
	modelType := ""
	for _, m := range models {
		if m.Name == primaryName || m.Name == strings.TrimSuffix(primaryName, "s") {
			modelType = m.Name
			break
		}
	}
	if modelType == "" && len(models) > 0 {
		modelType = models[0].Name
	}

	modelDir := filepath.Join(pkg.Out, packageToPath(pkg.ModelPackage))
	mapperDir := filepath.Join(pkg.Out, packageToPath(pkg.MapperPackage))

	// Models
	if err := os.MkdirAll(modelDir, 0755); err != nil {
		return err
	}
	for _, m := range models {
		if err := writeJavaModel(modelDir, m, pkg.ModelPackage); err != nil {
			return err
		}
	}

	// Mappers
	if err := os.MkdirAll(mapperDir, 0755); err != nil {
		return err
	}

	if err := writeJavaSharedMapper(mapperDir, mapperName, specs, modelType, pkg.ModelPackage, pkg.MapperPackage); err != nil {
		return err
	}
	for _, eng := range engs {
		enginePkg := pkg.MapperPackage
		engineDir := mapperDir
		if pkg.EngineSubPackage {
			enginePkg = pkg.MapperPackage + "." + eng.Name()
			engineDir = filepath.Join(mapperDir, eng.Name())
			if err := os.MkdirAll(engineDir, 0755); err != nil {
				return err
			}
		}
		if err := writeJavaEngineMapper(engineDir, enginePkg, mapperName, specs, modelType, pkg.ModelPackage, pkg.MapperPackage, eng); err != nil {
			return err
		}
	}

	// Factory
	return writeJavaFactory(mapperDir, mapperName, engs, pkg.MapperPackage, pkg.EngineSubPackage)
}

func writeJavaModel(dir string, model engines.Model, modelPkg string) error {
	path := filepath.Join(dir, model.Name+".java")
	content := javaGenModelFile(model, modelPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaSharedMapper(dir, mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string) error {
	path := filepath.Join(dir, mapperName+".java")
	content := javaGenSharedMapperFile(mapperName, specs, modelType, modelPkg, mapperPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaEngineMapper(dir, enginePkg, mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string, eng Engine) error {
	suffix := suffixForJava(eng.Name())
	path := filepath.Join(dir, mapperName+suffix+".java")
	content := javaGenEngineMapperFile(mapperName, specs, modelType, modelPkg, enginePkg, mapperPkg, eng)
	return os.WriteFile(path, []byte(content), 0644)
}

func writeJavaFactory(dir, mapperName string, engs []Engine, mapperPkg string, engineSubPkg bool) error {
	path := filepath.Join(dir, mapperName+"Factory.java")
	content := javaGenFactoryFile(mapperName, engs, mapperPkg, engineSubPkg)
	return os.WriteFile(path, []byte(content), 0644)
}

func javaGenModelFile(model engines.Model, modelPkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", modelPkg)

	imports := GenModelImports([]engines.Model{model})
	if imports != "" {
		b.WriteString(imports)
		b.WriteString("\n")
	}

	b.WriteString(GenModel(model))
	return b.String()
}

func javaGenSharedMapperFile(mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, mapperPkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", mapperPkg)

	addModelImports(&b, specs, modelPkg, mapperPkg)
	b.WriteString(GenMapperImports(specs))
	b.WriteString(GenSharedMapper(mapperName, specs, modelType))
	return b.String()
}

func javaGenEngineMapperFile(mapperName string, specs []engines.RunnerSpec, modelType, modelPkg, enginePkg, mapperPkg string, eng Engine) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", enginePkg)

	addModelImports(&b, specs, modelPkg, enginePkg)
	if enginePkg != mapperPkg {
		fmt.Fprintf(&b, "import %s.%s;\n", mapperPkg, mapperName)
	}
	b.WriteString(GenMapperImports(specs))

	suffix := suffixForJava(eng.Name())
	b.WriteString(GenEngineMapperHeader(mapperName, eng.Profile(), suffix))
	b.WriteString(eng.GenMapper(mapperName, specs, modelType))
	b.WriteString(GenEngineMapperFooter())
	return b.String()
}

// addModelImports writes import statements for model classes used in method signatures.
func addModelImports(b *strings.Builder, specs []engines.RunnerSpec, modelPkg, mapperPkg string) {
	if modelPkg == mapperPkg {
		return // same package, no import needed
	}
	imported := map[string]bool{}
	for _, spec := range specs {
		if spec.IsScalar {
			continue // scalars don't need model imports
		}
		mt := spec.ModelType
		if mt == "" {
			continue
		}
		if imported[mt] {
			continue
		}
		imported[mt] = true
		fmt.Fprintf(b, "import %s.%s;\n", modelPkg, mt)
	}
	// Also import model for RETURNING methods
	if len(specs) > 0 {
		for _, spec := range specs {
			if spec.Kind == engines.RunnerReturningScalar && !spec.IsScalar && spec.ModelType != "" {
				mt := spec.ModelType
				if !imported[mt] {
					fmt.Fprintf(b, "import %s.%s;\n", modelPkg, mt)
					imported[mt] = true
				}
			}
		}
	}
	b.WriteString("\n")
}

func javaGenFactoryFile(mapperName string, engs []Engine, mapperPkg string, engineSubPkg bool) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", mapperPkg)
	b.WriteString(GenFactory(mapperName, engs, mapperPkg, engineSubPkg))
	return b.String()
}

func packageToPath(pkg string) string {
	return strings.ReplaceAll(pkg, ".", "/")
}

func lastPackageSeg(pkg string) string {
	idx := strings.LastIndex(pkg, ".")
	if idx < 0 {
		return pkg
	}
	return pkg[idx+1:]
}

func mapperShortName(stem string) string {
	s := strings.ReplaceAll(stem, "-", "_")
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "") + "Mapper"
}

func suffixForJava(engineName string) string {
	switch engineName {
	case "pg":
		return "PG"
	case "mysql":
		return "MySQL"
	case "oracle":
		return "Oracle"
	case "mssql":
		return "MSSQL"
	default:
		return strings.ToUpper(engineName[:1]) + engineName[1:]
	}
}
