package java

import (
	"fmt"
	"strings"
)

// typeHandlerName returns the TypeHandler class name for a Java array type and
// dialect suffix (e.g. "LongArrayTypeHandler" + "PG").
func typeHandlerName(javaArrayType, dialectSuffix string) string {
	elem := strings.TrimSuffix(javaArrayType, "[]")
	switch elem {
	case "long":
		return "LongArrayTypeHandler" + dialectSuffix
	case "int":
		return "IntArrayTypeHandler" + dialectSuffix
	case "String":
		return "StringArrayTypeHandler" + dialectSuffix
	default:
		return "ArrayTypeHandler" + dialectSuffix
	}
}

// arraySQLTypeName returns the SQL array element type name used by the dialect's
// native array binding (PG createArrayOf / Oracle createARRAY).
func arraySQLTypeName(dialect, goType string) string {
	elem := strings.TrimPrefix(goType, "[]")
	switch dialect {
	case "pg":
		switch elem {
		case "string":
			return "text"
		case "int32":
			return "integer"
		case "float64":
			return "float8"
		default: // int64, int
			return "bigint"
		}
	case "oracle":
		switch elem {
		case "string":
			return "SYS.ODCIVARCHAR2LIST"
		default:
			return "SYS.ODCINUMBERLIST"
		}
	}
	return ""
}

// genTypeHandler generates a full MyBatis TypeHandler class mapping a Java array
// type to the dialect's wire format.
func genTypeHandler(dialect, pkg, className, javaArrayType, goType string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s;\n\n", pkg)

	b.WriteString("import org.apache.ibatis.type.BaseTypeHandler;\n")
	b.WriteString("import org.apache.ibatis.type.JdbcType;\n\n")
	b.WriteString("import java.sql.CallableStatement;\n")
	b.WriteString("import java.sql.PreparedStatement;\n")
	b.WriteString("import java.sql.ResultSet;\n")
	b.WriteString("import java.sql.SQLException;\n\n")

	elemType := strings.TrimSuffix(javaArrayType, "[]")
	isString := elemType == "String"
	primitive := elemType == "long" || elemType == "int"

	if dialect == "mysql" || dialect == "mssql" {
		b.WriteString("import com.fasterxml.jackson.databind.ObjectMapper;\n\n")
	}

	fmt.Fprintf(&b, "/** TypeHandler mapping {@code %s} to a %s array/JSON value. */\n", javaArrayType, strings.ToUpper(dialect))
	fmt.Fprintf(&b, "public class %s extends BaseTypeHandler<%s> {\n\n", className, javaArrayType)

	t := &thGen{}
	switch dialect {
	case "pg", "oracle":
		t.genArrayWrite(&b, dialect, elemType, primitive, goType)
		t.genArrayRead(&b, elemType, primitive, isString)
	case "mysql", "mssql":
		t.genJSONWrite(&b, javaArrayType)
		t.genJSONRead(&b, javaArrayType)
	}

	b.WriteString("}\n")
	return b.String()
}

type thGen struct{}

// genArrayWrite emits setNonNullParameter using native array binding (PG/Oracle).
func (g *thGen) genArrayWrite(b *strings.Builder, dialect, elemType string, primitive bool, goType string) {
	sqlType := arraySQLTypeName(dialect, goType)
	b.WriteString("    @Override\n")
	fmt.Fprintf(b, "    public void setNonNullParameter(PreparedStatement ps, int i, %s[] parameter, JdbcType jdbcType) throws SQLException {\n", elemType)
	b.WriteString("        Object[] boxed = new Object[parameter.length];\n")
	b.WriteString("        for (int j = 0; j < parameter.length; j++) {\n")
	b.WriteString("            boxed[j] = parameter[j];\n")
	b.WriteString("        }\n")
	if dialect == "oracle" {
		b.WriteString("        oracle.jdbc.OracleConnection conn = ps.getConnection().unwrap(oracle.jdbc.OracleConnection.class);\n")
		fmt.Fprintf(b, "        ps.setArray(i, conn.createARRAY(\"%s\", boxed));\n", sqlType)
	} else {
		fmt.Fprintf(b, "        ps.setArray(i, ps.getConnection().createArrayOf(\"%s\", boxed));\n", sqlType)
	}
	b.WriteString("    }\n\n")
}

// genArrayRead emits the three getNullableResult methods for native array types.
func (g *thGen) genArrayRead(b *strings.Builder, elemType string, primitive, isString bool) {
	for _, sig := range []struct{ code, args string }{
		{`getNullableResult(ResultSet rs, String columnName)`, `rs.getArray(columnName)`},
		{`getNullableResult(ResultSet rs, int columnIndex)`, `rs.getArray(columnIndex)`},
		{`getNullableResult(CallableStatement cs, int columnIndex)`, `cs.getArray(columnIndex)`},
	} {
		b.WriteString("    @Override\n")
		fmt.Fprintf(b, "    public %s[] %s throws SQLException {\n", elemType, sig.code)
		fmt.Fprintf(b, "        return toArray(%s);\n", sig.args)
		b.WriteString("    }\n\n")
	}

	b.WriteString("    private ")
	fmt.Fprintf(b, "%s[] toArray(java.sql.Array array) throws SQLException {\n", elemType)
	b.WriteString("        if (array == null) {\n")
	b.WriteString("            return null;\n")
	b.WriteString("        }\n")
	b.WriteString("        Object raw = array.getArray();\n")
	if isString {
		b.WriteString("        if (raw instanceof String[]) {\n")
		b.WriteString("            return (String[]) raw;\n")
		b.WriteString("        }\n")
	}
	fmt.Fprintf(b, "        Object[] items = (Object[]) raw;\n")
	fmt.Fprintf(b, "        %s[] out = new %s[items.length];\n", elemType, elemType)
	b.WriteString("        for (int j = 0; j < items.length; j++) {\n")
	if isString {
		b.WriteString("            out[j] = (String) items[j];\n")
	} else {
		b.WriteString("            out[j] = ((Number) items[j]).")
		if primitive {
			switch elemType {
			case "long":
				b.WriteString("longValue();\n")
			case "int":
				b.WriteString("intValue();\n")
			}
		} else {
			b.WriteString("longValue();\n")
		}
	}
	b.WriteString("        }\n")
	b.WriteString("        return out;\n")
	b.WriteString("    }\n\n")
}

// genJSONWrite emits setNonNullParameter using Jackson JSON serialization.
func (g *thGen) genJSONWrite(b *strings.Builder, javaArrayType string) {
	b.WriteString("    private static final ObjectMapper MAPPER = new ObjectMapper();\n\n")
	b.WriteString("    @Override\n")
	fmt.Fprintf(b, "    public void setNonNullParameter(PreparedStatement ps, int i, %s parameter, JdbcType jdbcType) throws SQLException {\n", javaArrayType)
	b.WriteString("        try {\n")
	b.WriteString("            ps.setString(i, MAPPER.writeValueAsString(parameter));\n")
	b.WriteString("        } catch (Exception e) {\n")
	b.WriteString("            throw new SQLException(e);\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
}

// genJSONRead emits the three getNullableResult methods using Jackson.
func (g *thGen) genJSONRead(b *strings.Builder, javaArrayType string) {
	for _, sig := range []struct{ code, args string }{
		{`getNullableResult(ResultSet rs, String columnName)`, `rs.getString(columnName)`},
		{`getNullableResult(ResultSet rs, int columnIndex)`, `rs.getString(columnIndex)`},
		{`getNullableResult(CallableStatement cs, int columnIndex)`, `cs.getString(columnIndex)`},
	} {
		b.WriteString("    @Override\n")
		fmt.Fprintf(b, "    public %s %s throws SQLException {\n", javaArrayType, sig.code)
		fmt.Fprintf(b, "        return fromJSON(%s);\n", sig.args)
		b.WriteString("    }\n\n")
	}

	b.WriteString("    private ")
	fmt.Fprintf(b, "%s fromJSON(String json) throws SQLException {\n", javaArrayType)
	b.WriteString("        if (json == null) {\n")
	b.WriteString("            return null;\n")
	b.WriteString("        }\n")
	b.WriteString("        try {\n")
	fmt.Fprintf(b, "            return MAPPER.readValue(json, %s.class);\n", javaArrayType)
	b.WriteString("        } catch (Exception e) {\n")
	b.WriteString("            throw new SQLException(e);\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
}
