// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"context"
	"database/sql"
)

const findByIDConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE id = @p1`

type findByIDMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByIDMSSQL) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByIDConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findByIDMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByIDMSSQL) withTx(tx *sql.Tx) findByIDRunner { return &findByIDMSSQL{stmt: tx.Stmt(r.stmt)} }

const findAllConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id`

type findAllMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findAllMSSQL) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findAllConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *findAllMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findAllMSSQL) withTx(tx *sql.Tx) findAllRunner { return &findAllMSSQL{stmt: tx.Stmt(r.stmt)} }

const findByCategoryConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE category = @p1 ORDER BY id`

type findByCategoryMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByCategoryMSSQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByCategoryConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *findByCategoryMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByCategoryMSSQL) withTx(tx *sql.Tx) findByCategoryRunner { return &findByCategoryMSSQL{stmt: tx.Stmt(r.stmt)} }

const listPagedConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id LIMIT @p1 OFFSET @p2`

type listPagedMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listPagedMSSQL) query(ctx context.Context, page_limit int32, page_offset int32) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listPagedConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, page_limit, page_offset)
}

func (r *listPagedMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listPagedMSSQL) withTx(tx *sql.Tx) listPagedRunner { return &listPagedMSSQL{stmt: tx.Stmt(r.stmt)} }

const insertItemConstMSSQL = `INSERT INTO items (name, category, price, stock) VALUES (@p1, @p2, @p3, @p4)`

type insertItemMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemMSSQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemMSSQL) withTx(tx *sql.Tx) insertItemRunner { return &insertItemMSSQL{stmt: tx.Stmt(r.stmt)} }

const insertItemRowsConstMSSQL = `INSERT INTO items (name, category, price, stock) VALUES (@p1, @p2, @p3, @p4)`

type insertItemRowsMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemRowsMSSQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemRowsConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemRowsMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemRowsMSSQL) withTx(tx *sql.Tx) insertItemRowsRunner { return &insertItemRowsMSSQL{stmt: tx.Stmt(r.stmt)} }

const insertAndReturnIDConstMSSQL = `INSERT INTO items (name, category, price, stock) OUTPUT INSERTED.id VALUES (@p1, @p2, @p3, @p4)`

type insertAndReturnIDMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertAndReturnIDMSSQL) execReturning(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	var id int64
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertAndReturnIDConstMSSQL); if err != nil { return 0, err } }
	row := r.stmt.QueryRowContext(ctx, name, category, price, stock)
	if err := row.Scan(&id); err != nil { return 0, err }
	return id, nil
}

func (r *insertAndReturnIDMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertAndReturnIDMSSQL) withTx(tx *sql.Tx) insertAndReturnIDRunner { return &insertAndReturnIDMSSQL{stmt: tx.Stmt(r.stmt)} }

const updateItemConstMSSQL = `UPDATE items SET name = @p1, price = @p2, updated_at = GETDATE() WHERE id = @p3`

type updateItemMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *updateItemMSSQL) exec(ctx context.Context, name string, price float64, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, updateItemConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, price, id)
}

func (r *updateItemMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *updateItemMSSQL) withTx(tx *sql.Tx) updateItemRunner { return &updateItemMSSQL{stmt: tx.Stmt(r.stmt)} }

const deleteItemConstMSSQL = `DELETE FROM items WHERE id = @p1`

type deleteItemMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemMSSQL) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemMSSQL) withTx(tx *sql.Tx) deleteItemRunner { return &deleteItemMSSQL{stmt: tx.Stmt(r.stmt)} }

const deleteItemRowsConstMSSQL = `DELETE FROM items WHERE id = @p1`

type deleteItemRowsMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemRowsMSSQL) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemRowsConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemRowsMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemRowsMSSQL) withTx(tx *sql.Tx) deleteItemRowsRunner { return &deleteItemRowsMSSQL{stmt: tx.Stmt(r.stmt)} }

const upsertItemConstMSSQL = `MERGE INTO items AS target
USING (VALUES (@p1, @p2, @p3, @p4)) AS src (name, category, price, stock)
ON target.name = src.name
WHEN NOT MATCHED THEN INSERT (name, category, price, stock) VALUES (src.name, src.category, src.price, src.stock)
WHEN MATCHED THEN UPDATE SET category = src.category, price = src.price, stock = src.stock;`

type upsertItemMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertItemMSSQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertItemConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *upsertItemMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertItemMSSQL) withTx(tx *sql.Tx) upsertItemRunner { return &upsertItemMSSQL{stmt: tx.Stmt(r.stmt)} }

const upsertIgnoreConstMSSQL = `MERGE INTO items AS target
USING (VALUES (@p1, @p2, 0, 0)) AS src (name, category, price, stock)
ON target.name = src.name
WHEN NOT MATCHED THEN INSERT (name, category, price, stock) VALUES (src.name, src.category, src.price, src.stock);`

type upsertIgnoreMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertIgnoreMSSQL) exec(ctx context.Context, name string, category string) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertIgnoreConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category)
}

func (r *upsertIgnoreMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertIgnoreMSSQL) withTx(tx *sql.Tx) upsertIgnoreRunner { return &upsertIgnoreMSSQL{stmt: tx.Stmt(r.stmt)} }

const searchByNameConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE name like @p1 ORDER BY id`

type searchByNameMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchByNameMSSQL) query(ctx context.Context, keyword string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchByNameConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword)
}

func (r *searchByNameMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchByNameMSSQL) withTx(tx *sql.Tx) searchByNameRunner { return &searchByNameMSSQL{stmt: tx.Stmt(r.stmt)} }

const searchOptionalConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (name like @p1 OR @p2 IS NULL) ORDER BY id`

type searchOptionalMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchOptionalMSSQL) query(ctx context.Context, keyword *string, keyword_1 *string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchOptionalConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword, keyword_1)
}

func (r *searchOptionalMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchOptionalMSSQL) withTx(tx *sql.Tx) searchOptionalRunner { return &searchOptionalMSSQL{stmt: tx.Stmt(r.stmt)} }

const countByCategoryConstMSSQL = `SELECT category, count(*) FROM items GROUP BY category HAVING count(*) >= 0 ORDER BY category`

type countByCategoryMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countByCategoryMSSQL) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countByCategoryConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *countByCategoryMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countByCategoryMSSQL) withTx(tx *sql.Tx) countByCategoryRunner { return &countByCategoryMSSQL{stmt: tx.Stmt(r.stmt)} }

const existsByNameConstMSSQL = `SELECT EXISTS (SELECT 1 FROM items WHERE name = @p1)`

type existsByNameMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *existsByNameMSSQL) query(ctx context.Context, name string) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, existsByNameConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, name), nil
}

func (r *existsByNameMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *existsByNameMSSQL) withTx(tx *sql.Tx) existsByNameRunner { return &existsByNameMSSQL{stmt: tx.Stmt(r.stmt)} }

const findByFiltersConstMSSQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (((category = @p1 OR @p2 IS NULL) AND (price >= @p3 OR @p4 IS NULL)) AND (is_active = @p5 OR @p6 IS NULL)) ORDER BY id`

type findByFiltersMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByFiltersMSSQL) query(ctx context.Context, category *string, category_1 *string, min_price *float64, min_price_1 *float64, is_active *bool, is_active_1 *bool) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByFiltersConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category, category_1, min_price, min_price_1, is_active, is_active_1)
}

func (r *findByFiltersMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByFiltersMSSQL) withTx(tx *sql.Tx) findByFiltersRunner { return &findByFiltersMSSQL{stmt: tx.Stmt(r.stmt)} }

const countAllConstMSSQL = `SELECT count(*) FROM items`

type countAllMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countAllMSSQL) query(ctx context.Context) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countAllConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx), nil
}

func (r *countAllMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countAllMSSQL) withTx(tx *sql.Tx) countAllRunner { return &countAllMSSQL{stmt: tx.Stmt(r.stmt)} }

const listNamesConstMSSQL = `SELECT name FROM items WHERE category = @p1 ORDER BY name`

type listNamesMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listNamesMSSQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listNamesConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listNamesMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listNamesMSSQL) withTx(tx *sql.Tx) listNamesRunner { return &listNamesMSSQL{stmt: tx.Stmt(r.stmt)} }

const listBriefConstMSSQL = `SELECT id, name, category FROM items WHERE category = @p1 ORDER BY id`

type listBriefMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listBriefMSSQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listBriefConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listBriefMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listBriefMSSQL) withTx(tx *sql.Tx) listBriefRunner { return &listBriefMSSQL{stmt: tx.Stmt(r.stmt)} }

const findWithExtraConstMSSQL = `SELECT id, name, category, price, stock, created_at FROM items WHERE id = @p1`

type findWithExtraMSSQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findWithExtraMSSQL) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findWithExtraConstMSSQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findWithExtraMSSQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findWithExtraMSSQL) withTx(tx *sql.Tx) findWithExtraRunner { return &findWithExtraMSSQL{stmt: tx.Stmt(r.stmt)} }


type itemsRunnerFactoryMSSQL struct {}


func (f *itemsRunnerFactoryMSSQL) newFindByID(db *sql.DB) findByIDRunner { return &findByIDMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newFindAll(db *sql.DB) findAllRunner { return &findAllMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newFindByCategory(db *sql.DB) findByCategoryRunner { return &findByCategoryMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newListPaged(db *sql.DB) listPagedRunner { return &listPagedMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newInsertItem(db *sql.DB) insertItemRunner { return &insertItemMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newInsertItemRows(db *sql.DB) insertItemRowsRunner { return &insertItemRowsMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newInsertAndReturnID(db *sql.DB) insertAndReturnIDRunner { return &insertAndReturnIDMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newUpdateItem(db *sql.DB) updateItemRunner { return &updateItemMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newDeleteItem(db *sql.DB) deleteItemRunner { return &deleteItemMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newDeleteItemRows(db *sql.DB) deleteItemRowsRunner { return &deleteItemRowsMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newUpsertItem(db *sql.DB) upsertItemRunner { return &upsertItemMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newUpsertIgnore(db *sql.DB) upsertIgnoreRunner { return &upsertIgnoreMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newSearchByName(db *sql.DB) searchByNameRunner { return &searchByNameMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newSearchOptional(db *sql.DB) searchOptionalRunner { return &searchOptionalMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newCountByCategory(db *sql.DB) countByCategoryRunner { return &countByCategoryMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newExistsByName(db *sql.DB) existsByNameRunner { return &existsByNameMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newFindByFilters(db *sql.DB) findByFiltersRunner { return &findByFiltersMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newCountAll(db *sql.DB) countAllRunner { return &countAllMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newListNames(db *sql.DB) listNamesRunner { return &listNamesMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newListBrief(db *sql.DB) listBriefRunner { return &listBriefMSSQL{db: db} }

func (f *itemsRunnerFactoryMSSQL) newFindWithExtra(db *sql.DB) findWithExtraRunner { return &findWithExtraMSSQL{db: db} }


