// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"context"
	"database/sql"
)

const findByIDConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE id = $1`

type findByIDPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByIDPG) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByIDConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findByIDPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByIDPG) withTx(tx *sql.Tx) findByIDRunner { return &findByIDPG{stmt: tx.Stmt(r.stmt)} }

const findAllConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id`

type findAllPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findAllPG) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findAllConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *findAllPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findAllPG) withTx(tx *sql.Tx) findAllRunner { return &findAllPG{stmt: tx.Stmt(r.stmt)} }

const findByCategoryConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE category = $1 ORDER BY id`

type findByCategoryPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByCategoryPG) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByCategoryConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *findByCategoryPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByCategoryPG) withTx(tx *sql.Tx) findByCategoryRunner { return &findByCategoryPG{stmt: tx.Stmt(r.stmt)} }

const listPagedConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id LIMIT $1 OFFSET $2`

type listPagedPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listPagedPG) query(ctx context.Context, page_limit int32, page_offset int32) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listPagedConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, page_limit, page_offset)
}

func (r *listPagedPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listPagedPG) withTx(tx *sql.Tx) listPagedRunner { return &listPagedPG{stmt: tx.Stmt(r.stmt)} }

const insertItemConstPG = `INSERT INTO items (name, category, price, stock) VALUES ($1, $2, $3, $4)`

type insertItemPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemPG) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemPG) withTx(tx *sql.Tx) insertItemRunner { return &insertItemPG{stmt: tx.Stmt(r.stmt)} }

const insertItemRowsConstPG = `INSERT INTO items (name, category, price, stock) VALUES ($1, $2, $3, $4)`

type insertItemRowsPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemRowsPG) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemRowsConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemRowsPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemRowsPG) withTx(tx *sql.Tx) insertItemRowsRunner { return &insertItemRowsPG{stmt: tx.Stmt(r.stmt)} }

const insertAndReturnIDConstPG = `INSERT INTO items (name, category, price, stock) VALUES ($1, $2, $3, $4) RETURNING id`

type insertAndReturnIDPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertAndReturnIDPG) execReturning(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	var id int64
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertAndReturnIDConstPG); if err != nil { return 0, err } }
	row := r.stmt.QueryRowContext(ctx, name, category, price, stock)
	if err := row.Scan(&id); err != nil { return 0, err }
	return id, nil
}

func (r *insertAndReturnIDPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertAndReturnIDPG) withTx(tx *sql.Tx) insertAndReturnIDRunner { return &insertAndReturnIDPG{stmt: tx.Stmt(r.stmt)} }

const updateItemConstPG = `UPDATE items SET name = $1, price = $2, updated_at = now() WHERE id = $3`

type updateItemPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *updateItemPG) exec(ctx context.Context, name string, price float64, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, updateItemConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, price, id)
}

func (r *updateItemPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *updateItemPG) withTx(tx *sql.Tx) updateItemRunner { return &updateItemPG{stmt: tx.Stmt(r.stmt)} }

const deleteItemConstPG = `DELETE FROM items WHERE id = $1`

type deleteItemPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemPG) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemPG) withTx(tx *sql.Tx) deleteItemRunner { return &deleteItemPG{stmt: tx.Stmt(r.stmt)} }

const deleteItemRowsConstPG = `DELETE FROM items WHERE id = $1`

type deleteItemRowsPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemRowsPG) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemRowsConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemRowsPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemRowsPG) withTx(tx *sql.Tx) deleteItemRowsRunner { return &deleteItemRowsPG{stmt: tx.Stmt(r.stmt)} }

const upsertItemConstPG = `INSERT INTO items (name, category, price, stock) VALUES ($1, $2, $3, $4)`

type upsertItemPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertItemPG) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertItemConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *upsertItemPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertItemPG) withTx(tx *sql.Tx) upsertItemRunner { return &upsertItemPG{stmt: tx.Stmt(r.stmt)} }

const upsertIgnoreConstPG = `INSERT INTO items (name, category, price, stock) VALUES ($1, $2, 0, 0)`

type upsertIgnorePG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertIgnorePG) exec(ctx context.Context, name string, category string) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertIgnoreConstPG); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category)
}

func (r *upsertIgnorePG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertIgnorePG) withTx(tx *sql.Tx) upsertIgnoreRunner { return &upsertIgnorePG{stmt: tx.Stmt(r.stmt)} }

const searchByNameConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE name like $1 ORDER BY id`

type searchByNamePG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchByNamePG) query(ctx context.Context, keyword string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchByNameConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword)
}

func (r *searchByNamePG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchByNamePG) withTx(tx *sql.Tx) searchByNameRunner { return &searchByNamePG{stmt: tx.Stmt(r.stmt)} }

const searchOptionalConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (name like $1 OR $2 IS NULL) ORDER BY id`

type searchOptionalPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchOptionalPG) query(ctx context.Context, keyword *string, keyword_1 *string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchOptionalConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword, keyword_1)
}

func (r *searchOptionalPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchOptionalPG) withTx(tx *sql.Tx) searchOptionalRunner { return &searchOptionalPG{stmt: tx.Stmt(r.stmt)} }

const countByCategoryConstPG = `SELECT category, count(*) FROM items GROUP BY category HAVING count(*) >= 0 ORDER BY category`

type countByCategoryPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countByCategoryPG) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countByCategoryConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *countByCategoryPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countByCategoryPG) withTx(tx *sql.Tx) countByCategoryRunner { return &countByCategoryPG{stmt: tx.Stmt(r.stmt)} }

const existsByNameConstPG = `SELECT EXISTS (SELECT 1 FROM items WHERE name = $1)`

type existsByNamePG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *existsByNamePG) query(ctx context.Context, name string) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, existsByNameConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, name), nil
}

func (r *existsByNamePG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *existsByNamePG) withTx(tx *sql.Tx) existsByNameRunner { return &existsByNamePG{stmt: tx.Stmt(r.stmt)} }

const findByFiltersConstPG = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (((category = $1 OR $2 IS NULL) AND (price >= $3 OR $4 IS NULL)) AND (is_active = $5 OR $6 IS NULL)) ORDER BY id`

type findByFiltersPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByFiltersPG) query(ctx context.Context, category *string, category_1 *string, min_price *float64, min_price_1 *float64, is_active *bool, is_active_1 *bool) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByFiltersConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category, category_1, min_price, min_price_1, is_active, is_active_1)
}

func (r *findByFiltersPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByFiltersPG) withTx(tx *sql.Tx) findByFiltersRunner { return &findByFiltersPG{stmt: tx.Stmt(r.stmt)} }

const countAllConstPG = `SELECT count(*) FROM items`

type countAllPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countAllPG) query(ctx context.Context) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countAllConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx), nil
}

func (r *countAllPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countAllPG) withTx(tx *sql.Tx) countAllRunner { return &countAllPG{stmt: tx.Stmt(r.stmt)} }

const listNamesConstPG = `SELECT name FROM items WHERE category = $1 ORDER BY name`

type listNamesPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listNamesPG) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listNamesConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listNamesPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listNamesPG) withTx(tx *sql.Tx) listNamesRunner { return &listNamesPG{stmt: tx.Stmt(r.stmt)} }

const listBriefConstPG = `SELECT id, name, category FROM items WHERE category = $1 ORDER BY id`

type listBriefPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listBriefPG) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listBriefConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listBriefPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listBriefPG) withTx(tx *sql.Tx) listBriefRunner { return &listBriefPG{stmt: tx.Stmt(r.stmt)} }

const findWithExtraConstPG = `SELECT id, name, category, price, stock, created_at FROM items WHERE id = $1`

type findWithExtraPG struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findWithExtraPG) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findWithExtraConstPG); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findWithExtraPG) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findWithExtraPG) withTx(tx *sql.Tx) findWithExtraRunner { return &findWithExtraPG{stmt: tx.Stmt(r.stmt)} }


type itemsRunnerFactoryPG struct {}


func (f *itemsRunnerFactoryPG) newFindByID(db *sql.DB) findByIDRunner { return &findByIDPG{db: db} }

func (f *itemsRunnerFactoryPG) newFindAll(db *sql.DB) findAllRunner { return &findAllPG{db: db} }

func (f *itemsRunnerFactoryPG) newFindByCategory(db *sql.DB) findByCategoryRunner { return &findByCategoryPG{db: db} }

func (f *itemsRunnerFactoryPG) newListPaged(db *sql.DB) listPagedRunner { return &listPagedPG{db: db} }

func (f *itemsRunnerFactoryPG) newInsertItem(db *sql.DB) insertItemRunner { return &insertItemPG{db: db} }

func (f *itemsRunnerFactoryPG) newInsertItemRows(db *sql.DB) insertItemRowsRunner { return &insertItemRowsPG{db: db} }

func (f *itemsRunnerFactoryPG) newInsertAndReturnID(db *sql.DB) insertAndReturnIDRunner { return &insertAndReturnIDPG{db: db} }

func (f *itemsRunnerFactoryPG) newUpdateItem(db *sql.DB) updateItemRunner { return &updateItemPG{db: db} }

func (f *itemsRunnerFactoryPG) newDeleteItem(db *sql.DB) deleteItemRunner { return &deleteItemPG{db: db} }

func (f *itemsRunnerFactoryPG) newDeleteItemRows(db *sql.DB) deleteItemRowsRunner { return &deleteItemRowsPG{db: db} }

func (f *itemsRunnerFactoryPG) newUpsertItem(db *sql.DB) upsertItemRunner { return &upsertItemPG{db: db} }

func (f *itemsRunnerFactoryPG) newUpsertIgnore(db *sql.DB) upsertIgnoreRunner { return &upsertIgnorePG{db: db} }

func (f *itemsRunnerFactoryPG) newSearchByName(db *sql.DB) searchByNameRunner { return &searchByNamePG{db: db} }

func (f *itemsRunnerFactoryPG) newSearchOptional(db *sql.DB) searchOptionalRunner { return &searchOptionalPG{db: db} }

func (f *itemsRunnerFactoryPG) newCountByCategory(db *sql.DB) countByCategoryRunner { return &countByCategoryPG{db: db} }

func (f *itemsRunnerFactoryPG) newExistsByName(db *sql.DB) existsByNameRunner { return &existsByNamePG{db: db} }

func (f *itemsRunnerFactoryPG) newFindByFilters(db *sql.DB) findByFiltersRunner { return &findByFiltersPG{db: db} }

func (f *itemsRunnerFactoryPG) newCountAll(db *sql.DB) countAllRunner { return &countAllPG{db: db} }

func (f *itemsRunnerFactoryPG) newListNames(db *sql.DB) listNamesRunner { return &listNamesPG{db: db} }

func (f *itemsRunnerFactoryPG) newListBrief(db *sql.DB) listBriefRunner { return &listBriefPG{db: db} }

func (f *itemsRunnerFactoryPG) newFindWithExtra(db *sql.DB) findWithExtraRunner { return &findWithExtraPG{db: db} }


