// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"fmt"
	"context"
	"database/sql"
)

// ── Runner interfaces ──

type findByIDRunner interface {
	query(ctx context.Context, id int64) (*sql.Row, error)
	close() error
	withTx(tx *sql.Tx) findByIDRunner
}

type findAllRunner interface {
	query(ctx context.Context) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) findAllRunner
}

type findByCategoryRunner interface {
	query(ctx context.Context, category string) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) findByCategoryRunner
}

type listPagedRunner interface {
	query(ctx context.Context, page_limit int32, page_offset int32) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) listPagedRunner
}

type insertItemRunner interface {
	exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) insertItemRunner
}

type insertItemRowsRunner interface {
	exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) insertItemRowsRunner
}

type insertAndReturnIDRunner interface {
	execReturning(ctx context.Context, name string, category string, price float64, stock int32) (int64, error)
	close() error
	withTx(tx *sql.Tx) insertAndReturnIDRunner
}

type updateItemRunner interface {
	exec(ctx context.Context, name string, price float64, id int64) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) updateItemRunner
}

type deleteItemRunner interface {
	exec(ctx context.Context, id int64) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) deleteItemRunner
}

type deleteItemRowsRunner interface {
	exec(ctx context.Context, id int64) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) deleteItemRowsRunner
}

type upsertItemRunner interface {
	exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) upsertItemRunner
}

type upsertIgnoreRunner interface {
	exec(ctx context.Context, name string, category string) (sql.Result, error)
	close() error
	withTx(tx *sql.Tx) upsertIgnoreRunner
}

type searchByNameRunner interface {
	query(ctx context.Context, keyword string) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) searchByNameRunner
}

type searchOptionalRunner interface {
	query(ctx context.Context, keyword *string, keyword_1 *string) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) searchOptionalRunner
}

type countByCategoryRunner interface {
	query(ctx context.Context) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) countByCategoryRunner
}

type existsByNameRunner interface {
	query(ctx context.Context, name string) (*sql.Row, error)
	close() error
	withTx(tx *sql.Tx) existsByNameRunner
}

type findByFiltersRunner interface {
	query(ctx context.Context, category *string, category_1 *string, min_price *float64, min_price_1 *float64, is_active *bool, is_active_1 *bool) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) findByFiltersRunner
}

type countAllRunner interface {
	query(ctx context.Context) (*sql.Row, error)
	close() error
	withTx(tx *sql.Tx) countAllRunner
}

type listNamesRunner interface {
	query(ctx context.Context, category string) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) listNamesRunner
}

type listBriefRunner interface {
	query(ctx context.Context, category string) (*sql.Rows, error)
	close() error
	withTx(tx *sql.Tx) listBriefRunner
}

type findWithExtraRunner interface {
	query(ctx context.Context, id int64) (*sql.Row, error)
	close() error
	withTx(tx *sql.Tx) findWithExtraRunner
}

// ── Factory interface ──

type itemsRunnerFactory interface {
	newFindByID(db *sql.DB) findByIDRunner
	newFindAll(db *sql.DB) findAllRunner
	newFindByCategory(db *sql.DB) findByCategoryRunner
	newListPaged(db *sql.DB) listPagedRunner
	newInsertItem(db *sql.DB) insertItemRunner
	newInsertItemRows(db *sql.DB) insertItemRowsRunner
	newInsertAndReturnID(db *sql.DB) insertAndReturnIDRunner
	newUpdateItem(db *sql.DB) updateItemRunner
	newDeleteItem(db *sql.DB) deleteItemRunner
	newDeleteItemRows(db *sql.DB) deleteItemRowsRunner
	newUpsertItem(db *sql.DB) upsertItemRunner
	newUpsertIgnore(db *sql.DB) upsertIgnoreRunner
	newSearchByName(db *sql.DB) searchByNameRunner
	newSearchOptional(db *sql.DB) searchOptionalRunner
	newCountByCategory(db *sql.DB) countByCategoryRunner
	newExistsByName(db *sql.DB) existsByNameRunner
	newFindByFilters(db *sql.DB) findByFiltersRunner
	newCountAll(db *sql.DB) countAllRunner
	newListNames(db *sql.DB) listNamesRunner
	newListBrief(db *sql.DB) listBriefRunner
	newFindWithExtra(db *sql.DB) findWithExtraRunner
}

// ── queries struct ──

type itemsQueries struct {
	db *sql.DB
	findByID findByIDRunner
	findAll findAllRunner
	findByCategory findByCategoryRunner
	listPaged listPagedRunner
	insertItem insertItemRunner
	insertItemRows insertItemRowsRunner
	insertAndReturnID insertAndReturnIDRunner
	updateItem updateItemRunner
	deleteItem deleteItemRunner
	deleteItemRows deleteItemRowsRunner
	upsertItem upsertItemRunner
	upsertIgnore upsertIgnoreRunner
	searchByName searchByNameRunner
	searchOptional searchOptionalRunner
	countByCategory countByCategoryRunner
	existsByName existsByNameRunner
	findByFilters findByFiltersRunner
	countAll countAllRunner
	listNames listNamesRunner
	listBrief listBriefRunner
	findWithExtra findWithExtraRunner
}

var _ ItemsQuerier = (*itemsQueries)(nil)

func newitemsQueries(db *sql.DB, f itemsRunnerFactory) *itemsQueries {
	return &itemsQueries{
		db: db,
		findByID: f.newFindByID(db),
		findAll: f.newFindAll(db),
		findByCategory: f.newFindByCategory(db),
		listPaged: f.newListPaged(db),
		insertItem: f.newInsertItem(db),
		insertItemRows: f.newInsertItemRows(db),
		insertAndReturnID: f.newInsertAndReturnID(db),
		updateItem: f.newUpdateItem(db),
		deleteItem: f.newDeleteItem(db),
		deleteItemRows: f.newDeleteItemRows(db),
		upsertItem: f.newUpsertItem(db),
		upsertIgnore: f.newUpsertIgnore(db),
		searchByName: f.newSearchByName(db),
		searchOptional: f.newSearchOptional(db),
		countByCategory: f.newCountByCategory(db),
		existsByName: f.newExistsByName(db),
		findByFilters: f.newFindByFilters(db),
		countAll: f.newCountAll(db),
		listNames: f.newListNames(db),
		listBrief: f.newListBrief(db),
		findWithExtra: f.newFindWithExtra(db),
	}
}

var factorys = map[string]itemsRunnerFactory{
	"postgres": &itemsRunnerFactoryPG{},
	"oracle": &itemsRunnerFactoryOracle{},
	"mysql": &itemsRunnerFactoryMySQL{},
	"sqlserver": &itemsRunnerFactoryMSSQL{},
}

func New(db *sql.DB, driver string) (ItemsQuerier, error) {
	f, ok := factorys[driver]
	if !ok {
		return nil, fmt.Errorf("sqlgen: unsupported driver %q", driver)
	}
	return newitemsQueries(db, f), nil
}

// ── 公共方法 ──

func (q *itemsQueries) FindByID(ctx context.Context, id int64) (*Item, error) {
	row, err := q.findByID.query(ctx, id)
	if err != nil { return nil, err }
	var r Item
	var _ns1 sql.NullString
	var _ns2 sql.NullString
	var _ns3 sql.NullTime
	var _ns4 sql.NullTime
	if err := row.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
	r.Name = _ns1.String
	r.Category = _ns2.String
	r.CreatedAt = _ns3.Time
	r.UpdatedAt = _ns4.Time
	return &r, nil
}

func (q *itemsQueries) FindAll(ctx context.Context) ([]*Item, error) {
	rows, err := q.findAll.query(ctx)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) FindByCategory(ctx context.Context, category string) ([]*Item, error) {
	rows, err := q.findByCategory.query(ctx, category)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) ListPaged(ctx context.Context, page_limit int32, page_offset int32) ([]*Item, error) {
	rows, err := q.listPaged.query(ctx, page_limit, page_offset)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) InsertItem(ctx context.Context, name string, category string, price float64, stock int32) (error) {
	_, err := q.insertItem.exec(ctx, name, category, price, stock)
	return err
}

func (q *itemsQueries) InsertItemRows(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	result, err := q.insertItemRows.exec(ctx, name, category, price, stock)
	if err != nil { return 0, err }
	return result.RowsAffected()
}

func (q *itemsQueries) InsertAndReturnID(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	return q.insertAndReturnID.execReturning(ctx, name, category, price, stock)
}

func (q *itemsQueries) UpdateItem(ctx context.Context, name string, price float64, id int64) (error) {
	_, err := q.updateItem.exec(ctx, name, price, id)
	return err
}

func (q *itemsQueries) DeleteItem(ctx context.Context, id int64) (error) {
	_, err := q.deleteItem.exec(ctx, id)
	return err
}

func (q *itemsQueries) DeleteItemRows(ctx context.Context, id int64) (int64, error) {
	result, err := q.deleteItemRows.exec(ctx, id)
	if err != nil { return 0, err }
	return result.RowsAffected()
}

func (q *itemsQueries) UpsertItem(ctx context.Context, name string, category string, price float64, stock int32) (error) {
	_, err := q.upsertItem.exec(ctx, name, category, price, stock)
	return err
}

func (q *itemsQueries) UpsertIgnore(ctx context.Context, name string, category string) (error) {
	_, err := q.upsertIgnore.exec(ctx, name, category)
	return err
}

func (q *itemsQueries) SearchByName(ctx context.Context, keyword string) ([]*Item, error) {
	rows, err := q.searchByName.query(ctx, keyword)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) SearchOptional(ctx context.Context, keyword *string) ([]*Item, error) {
	rows, err := q.searchOptional.query(ctx, keyword, keyword)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) CountByCategory(ctx context.Context) ([]*CatCount, error) {
	rows, err := q.countByCategory.query(ctx)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*CatCount
	for rows.Next() {
		var r CatCount
		var _ns1 sql.NullString
		if err := rows.Scan(&_ns1, &r.Cnt); err != nil { return nil, err }
		r.Category = _ns1.String
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) ExistsByName(ctx context.Context, name string) (*ExistsByName, error) {
	row, err := q.existsByName.query(ctx, name)
	if err != nil { return nil, err }
	var r ExistsByName
	if err := row.Scan(&r.Exists); err != nil { return nil, err }
	return &r, nil
}

func (q *itemsQueries) FindByFilters(ctx context.Context, category *string, min_price *float64, is_active *bool) ([]*Item, error) {
	rows, err := q.findByFilters.query(ctx, category, category, min_price, min_price, is_active, is_active)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var r Item
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		var _ns3 sql.NullTime
		var _ns4 sql.NullTime
		if err := rows.Scan(&r.ID, &_ns1, &_ns2, &r.Price, &r.Stock, &r.IsActive, &_ns3, &_ns4); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		r.CreatedAt = _ns3.Time
		r.UpdatedAt = _ns4.Time
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) CountAll(ctx context.Context) (int64, error) {
	row, err := q.countAll.query(ctx)
	if err != nil { return 0, err }
	var item int64
	if err := row.Scan(&item); err != nil { return 0, err }
	return item, nil
}

func (q *itemsQueries) ListNames(ctx context.Context, category string) ([]string, error) {
	rows, err := q.listNames.query(ctx, category)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item string
		if err := rows.Scan(&item); err != nil { return nil, err }
		items = append(items, item)
	}
	return items, rows.Err()
}

func (q *itemsQueries) ListBrief(ctx context.Context, category string) ([]*ItemBrief, error) {
	rows, err := q.listBrief.query(ctx, category)
	if err != nil { return nil, err }
	defer rows.Close()
	var items []*ItemBrief
	for rows.Next() {
		var r ItemBrief
		var _ns1 sql.NullString
		var _ns2 sql.NullString
		if err := rows.Scan(&r.ID, &_ns1, &_ns2); err != nil { return nil, err }
		r.Name = _ns1.String
		r.Category = _ns2.String
		items = append(items, &r)
	}
	return items, rows.Err()
}

func (q *itemsQueries) FindWithExtra(ctx context.Context, id int64) (*ItemBrief, error) {
	row, err := q.findWithExtra.query(ctx, id)
	if err != nil { return nil, err }
	var r ItemBrief
	var _ns1 sql.NullString
	var _ns2 sql.NullString
	var _d1 interface{}
	var _d2 interface{}
	var _d3 interface{}
	if err := row.Scan(&r.ID, &_ns1, &_ns2, &_d1, &_d2, &_d3); err != nil { return nil, err }
	r.Name = _ns1.String
	r.Category = _ns2.String
	return &r, nil
}

func (q *itemsQueries) Close() error {
	q.findByID.close()
	q.findAll.close()
	q.findByCategory.close()
	q.listPaged.close()
	q.insertItem.close()
	q.insertItemRows.close()
	q.insertAndReturnID.close()
	q.updateItem.close()
	q.deleteItem.close()
	q.deleteItemRows.close()
	q.upsertItem.close()
	q.upsertIgnore.close()
	q.searchByName.close()
	q.searchOptional.close()
	q.countByCategory.close()
	q.existsByName.close()
	q.findByFilters.close()
	q.countAll.close()
	q.listNames.close()
	q.listBrief.close()
	q.findWithExtra.close()
	return nil
}

func (q *itemsQueries) WithTx(tx *sql.Tx) ItemsQuerier {
	return &itemsQueries{
		db: q.db,
		findByID: q.findByID.withTx(tx),
		findAll: q.findAll.withTx(tx),
		findByCategory: q.findByCategory.withTx(tx),
		listPaged: q.listPaged.withTx(tx),
		insertItem: q.insertItem.withTx(tx),
		insertItemRows: q.insertItemRows.withTx(tx),
		insertAndReturnID: q.insertAndReturnID.withTx(tx),
		updateItem: q.updateItem.withTx(tx),
		deleteItem: q.deleteItem.withTx(tx),
		deleteItemRows: q.deleteItemRows.withTx(tx),
		upsertItem: q.upsertItem.withTx(tx),
		upsertIgnore: q.upsertIgnore.withTx(tx),
		searchByName: q.searchByName.withTx(tx),
		searchOptional: q.searchOptional.withTx(tx),
		countByCategory: q.countByCategory.withTx(tx),
		existsByName: q.existsByName.withTx(tx),
		findByFilters: q.findByFilters.withTx(tx),
		countAll: q.countAll.withTx(tx),
		listNames: q.listNames.withTx(tx),
		listBrief: q.listBrief.withTx(tx),
		findWithExtra: q.findWithExtra.withTx(tx),
	}
}

type ItemsQuerier interface {
	FindByID(ctx context.Context, id int64) (*Item, error)
	FindAll(ctx context.Context) ([]*Item, error)
	FindByCategory(ctx context.Context, category string) ([]*Item, error)
	ListPaged(ctx context.Context, page_limit int32, page_offset int32) ([]*Item, error)
	InsertItem(ctx context.Context, name string, category string, price float64, stock int32) (error)
	InsertItemRows(ctx context.Context, name string, category string, price float64, stock int32) (int64, error)
	InsertAndReturnID(ctx context.Context, name string, category string, price float64, stock int32) (int64, error)
	UpdateItem(ctx context.Context, name string, price float64, id int64) (error)
	DeleteItem(ctx context.Context, id int64) (error)
	DeleteItemRows(ctx context.Context, id int64) (int64, error)
	UpsertItem(ctx context.Context, name string, category string, price float64, stock int32) (error)
	UpsertIgnore(ctx context.Context, name string, category string) (error)
	SearchByName(ctx context.Context, keyword string) ([]*Item, error)
	SearchOptional(ctx context.Context, keyword *string) ([]*Item, error)
	CountByCategory(ctx context.Context) ([]*CatCount, error)
	ExistsByName(ctx context.Context, name string) (*ExistsByName, error)
	FindByFilters(ctx context.Context, category *string, min_price *float64, is_active *bool) ([]*Item, error)
	CountAll(ctx context.Context) (int64, error)
	ListNames(ctx context.Context, category string) ([]string, error)
	ListBrief(ctx context.Context, category string) ([]*ItemBrief, error)
	FindWithExtra(ctx context.Context, id int64) (*ItemBrief, error)
	Close() error
}
