// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"context"
	"database/sql"
)

const findByIDConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE id = :1`

type findByIDOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByIDOracle) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByIDConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findByIDOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByIDOracle) withTx(tx *sql.Tx) findByIDRunner { return &findByIDOracle{stmt: tx.Stmt(r.stmt)} }

const findAllConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id`

type findAllOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findAllOracle) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findAllConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *findAllOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findAllOracle) withTx(tx *sql.Tx) findAllRunner { return &findAllOracle{stmt: tx.Stmt(r.stmt)} }

const findByCategoryConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE category = :1 ORDER BY id`

type findByCategoryOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByCategoryOracle) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByCategoryConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *findByCategoryOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByCategoryOracle) withTx(tx *sql.Tx) findByCategoryRunner { return &findByCategoryOracle{stmt: tx.Stmt(r.stmt)} }

const listPagedConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY`

type listPagedOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listPagedOracle) query(ctx context.Context, page_limit int32, page_offset int32) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listPagedConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, page_offset, page_limit)
}

func (r *listPagedOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listPagedOracle) withTx(tx *sql.Tx) listPagedRunner { return &listPagedOracle{stmt: tx.Stmt(r.stmt)} }

const insertItemConstOracle = `INSERT INTO items (name, category, price, stock) VALUES (:1, :2, :3, :4)`

type insertItemOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemOracle) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemOracle) withTx(tx *sql.Tx) insertItemRunner { return &insertItemOracle{stmt: tx.Stmt(r.stmt)} }

const insertItemRowsConstOracle = `INSERT INTO items (name, category, price, stock) VALUES (:1, :2, :3, :4)`

type insertItemRowsOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemRowsOracle) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemRowsConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemRowsOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemRowsOracle) withTx(tx *sql.Tx) insertItemRowsRunner { return &insertItemRowsOracle{stmt: tx.Stmt(r.stmt)} }

const insertAndReturnIDConstOracle = `INSERT INTO items (name, category, price, stock) VALUES (:1, :2, :3, :4) RETURNING id INTO :out0`

type insertAndReturnIDOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertAndReturnIDOracle) execReturning(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	var id int64
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertAndReturnIDConstOracle); if err != nil { return 0, err } }
	if _, err := r.stmt.ExecContext(ctx, name, category, price, stock, &id); err != nil { return 0, err }
	return id, nil
}

func (r *insertAndReturnIDOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertAndReturnIDOracle) withTx(tx *sql.Tx) insertAndReturnIDRunner { return &insertAndReturnIDOracle{stmt: tx.Stmt(r.stmt)} }

const updateItemConstOracle = `UPDATE items SET name = :1, price = :2, updated_at = SYSDATE WHERE id = :3`

type updateItemOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *updateItemOracle) exec(ctx context.Context, name string, price float64, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, updateItemConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, price, id)
}

func (r *updateItemOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *updateItemOracle) withTx(tx *sql.Tx) updateItemRunner { return &updateItemOracle{stmt: tx.Stmt(r.stmt)} }

const deleteItemConstOracle = `DELETE FROM items WHERE id = :1`

type deleteItemOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemOracle) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemOracle) withTx(tx *sql.Tx) deleteItemRunner { return &deleteItemOracle{stmt: tx.Stmt(r.stmt)} }

const deleteItemRowsConstOracle = `DELETE FROM items WHERE id = :1`

type deleteItemRowsOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemRowsOracle) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemRowsConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemRowsOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemRowsOracle) withTx(tx *sql.Tx) deleteItemRowsRunner { return &deleteItemRowsOracle{stmt: tx.Stmt(r.stmt)} }

const upsertItemConstOracle = `MERGE INTO items t
USING (SELECT :1 AS name, :2 AS category, :3 AS price, :4 AS stock FROM dual) s
ON (t.name = s.name)
WHEN NOT MATCHED THEN
    INSERT (name, category, price, stock) VALUES (s.name, s.category, s.price, s.stock)
WHEN MATCHED THEN
    UPDATE SET category = s.category, price = s.price, stock = s.stock`

type upsertItemOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertItemOracle) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertItemConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *upsertItemOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertItemOracle) withTx(tx *sql.Tx) upsertItemRunner { return &upsertItemOracle{stmt: tx.Stmt(r.stmt)} }

const upsertIgnoreConstOracle = `MERGE INTO items t
USING (SELECT :1 AS name, :2 AS category, 0 AS price, 0 AS stock FROM dual) s
ON (t.name = s.name)
WHEN NOT MATCHED THEN
    INSERT (name, category, price, stock) VALUES (s.name, s.category, s.price, s.stock)`

type upsertIgnoreOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertIgnoreOracle) exec(ctx context.Context, name string, category string) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertIgnoreConstOracle); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category)
}

func (r *upsertIgnoreOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertIgnoreOracle) withTx(tx *sql.Tx) upsertIgnoreRunner { return &upsertIgnoreOracle{stmt: tx.Stmt(r.stmt)} }

const searchByNameConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE LOWER(name) LIKE LOWER(:1) ORDER BY id`

type searchByNameOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchByNameOracle) query(ctx context.Context, keyword string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchByNameConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword)
}

func (r *searchByNameOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchByNameOracle) withTx(tx *sql.Tx) searchByNameRunner { return &searchByNameOracle{stmt: tx.Stmt(r.stmt)} }

const searchOptionalConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (LOWER(name) LIKE LOWER(:1) OR :2 IS NULL) ORDER BY id`

type searchOptionalOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchOptionalOracle) query(ctx context.Context, keyword *string, keyword_1 *string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchOptionalConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword, keyword_1)
}

func (r *searchOptionalOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchOptionalOracle) withTx(tx *sql.Tx) searchOptionalRunner { return &searchOptionalOracle{stmt: tx.Stmt(r.stmt)} }

const countByCategoryConstOracle = `SELECT category, count(*) FROM items GROUP BY category HAVING count(*) >= 0 ORDER BY category`

type countByCategoryOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countByCategoryOracle) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countByCategoryConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *countByCategoryOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countByCategoryOracle) withTx(tx *sql.Tx) countByCategoryRunner { return &countByCategoryOracle{stmt: tx.Stmt(r.stmt)} }

const existsByNameConstOracle = `SELECT EXISTS (SELECT 1 FROM items WHERE name = :1) FROM dual`

type existsByNameOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *existsByNameOracle) query(ctx context.Context, name string) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, existsByNameConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, name), nil
}

func (r *existsByNameOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *existsByNameOracle) withTx(tx *sql.Tx) existsByNameRunner { return &existsByNameOracle{stmt: tx.Stmt(r.stmt)} }

const findByFiltersConstOracle = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (((category = :1 OR :2 IS NULL) AND (price >= :3 OR :4 IS NULL)) AND (is_active = :5 OR :6 IS NULL)) ORDER BY id`

type findByFiltersOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByFiltersOracle) query(ctx context.Context, category *string, category_1 *string, min_price *float64, min_price_1 *float64, is_active *bool, is_active_1 *bool) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByFiltersConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category, category_1, min_price, min_price_1, is_active, is_active_1)
}

func (r *findByFiltersOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByFiltersOracle) withTx(tx *sql.Tx) findByFiltersRunner { return &findByFiltersOracle{stmt: tx.Stmt(r.stmt)} }

const countAllConstOracle = `SELECT count(*) FROM items`

type countAllOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countAllOracle) query(ctx context.Context) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countAllConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx), nil
}

func (r *countAllOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countAllOracle) withTx(tx *sql.Tx) countAllRunner { return &countAllOracle{stmt: tx.Stmt(r.stmt)} }

const listNamesConstOracle = `SELECT name FROM items WHERE category = :1 ORDER BY name`

type listNamesOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listNamesOracle) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listNamesConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listNamesOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listNamesOracle) withTx(tx *sql.Tx) listNamesRunner { return &listNamesOracle{stmt: tx.Stmt(r.stmt)} }

const listBriefConstOracle = `SELECT id, name, category FROM items WHERE category = :1 ORDER BY id`

type listBriefOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listBriefOracle) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listBriefConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listBriefOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listBriefOracle) withTx(tx *sql.Tx) listBriefRunner { return &listBriefOracle{stmt: tx.Stmt(r.stmt)} }

const findWithExtraConstOracle = `SELECT id, name, category, price, stock, created_at FROM items WHERE id = :1`

type findWithExtraOracle struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findWithExtraOracle) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findWithExtraConstOracle); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findWithExtraOracle) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findWithExtraOracle) withTx(tx *sql.Tx) findWithExtraRunner { return &findWithExtraOracle{stmt: tx.Stmt(r.stmt)} }


type itemsRunnerFactoryOracle struct {}


func (f *itemsRunnerFactoryOracle) newFindByID(db *sql.DB) findByIDRunner { return &findByIDOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newFindAll(db *sql.DB) findAllRunner { return &findAllOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newFindByCategory(db *sql.DB) findByCategoryRunner { return &findByCategoryOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newListPaged(db *sql.DB) listPagedRunner { return &listPagedOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newInsertItem(db *sql.DB) insertItemRunner { return &insertItemOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newInsertItemRows(db *sql.DB) insertItemRowsRunner { return &insertItemRowsOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newInsertAndReturnID(db *sql.DB) insertAndReturnIDRunner { return &insertAndReturnIDOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newUpdateItem(db *sql.DB) updateItemRunner { return &updateItemOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newDeleteItem(db *sql.DB) deleteItemRunner { return &deleteItemOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newDeleteItemRows(db *sql.DB) deleteItemRowsRunner { return &deleteItemRowsOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newUpsertItem(db *sql.DB) upsertItemRunner { return &upsertItemOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newUpsertIgnore(db *sql.DB) upsertIgnoreRunner { return &upsertIgnoreOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newSearchByName(db *sql.DB) searchByNameRunner { return &searchByNameOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newSearchOptional(db *sql.DB) searchOptionalRunner { return &searchOptionalOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newCountByCategory(db *sql.DB) countByCategoryRunner { return &countByCategoryOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newExistsByName(db *sql.DB) existsByNameRunner { return &existsByNameOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newFindByFilters(db *sql.DB) findByFiltersRunner { return &findByFiltersOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newCountAll(db *sql.DB) countAllRunner { return &countAllOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newListNames(db *sql.DB) listNamesRunner { return &listNamesOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newListBrief(db *sql.DB) listBriefRunner { return &listBriefOracle{db: db} }

func (f *itemsRunnerFactoryOracle) newFindWithExtra(db *sql.DB) findWithExtraRunner { return &findWithExtraOracle{db: db} }


