// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"context"
	"database/sql"
)

const findByIDConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE id = ?`

type findByIDMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByIDMySQL) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByIDConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findByIDMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByIDMySQL) withTx(tx *sql.Tx) findByIDRunner { return &findByIDMySQL{stmt: tx.Stmt(r.stmt)} }

const findAllConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id`

type findAllMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findAllMySQL) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findAllConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *findAllMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findAllMySQL) withTx(tx *sql.Tx) findAllRunner { return &findAllMySQL{stmt: tx.Stmt(r.stmt)} }

const findByCategoryConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE category = ? ORDER BY id`

type findByCategoryMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByCategoryMySQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByCategoryConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *findByCategoryMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByCategoryMySQL) withTx(tx *sql.Tx) findByCategoryRunner { return &findByCategoryMySQL{stmt: tx.Stmt(r.stmt)} }

const listPagedConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items ORDER BY id LIMIT ? OFFSET ?`

type listPagedMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listPagedMySQL) query(ctx context.Context, page_limit int32, page_offset int32) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listPagedConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, page_limit, page_offset)
}

func (r *listPagedMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listPagedMySQL) withTx(tx *sql.Tx) listPagedRunner { return &listPagedMySQL{stmt: tx.Stmt(r.stmt)} }

const insertItemConstMySQL = `INSERT INTO items (name, category, price, stock) VALUES (?, ?, ?, ?)`

type insertItemMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemMySQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemMySQL) withTx(tx *sql.Tx) insertItemRunner { return &insertItemMySQL{stmt: tx.Stmt(r.stmt)} }

const insertItemRowsConstMySQL = `INSERT INTO items (name, category, price, stock) VALUES (?, ?, ?, ?)`

type insertItemRowsMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *insertItemRowsMySQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, insertItemRowsConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *insertItemRowsMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *insertItemRowsMySQL) withTx(tx *sql.Tx) insertItemRowsRunner { return &insertItemRowsMySQL{stmt: tx.Stmt(r.stmt)} }

const insertAndReturnIDConstMySQL = `INSERT INTO items (name, category, price, stock) VALUES (?, ?, ?, ?)`

const insertAndReturnIDSelectConstMySQL = `SELECT LAST_INSERT_ID()`

type insertAndReturnIDMySQL struct {
	execStmt  *sql.Stmt
	queryStmt *sql.Stmt
	db        *sql.DB
}

func (r *insertAndReturnIDMySQL) execReturning(ctx context.Context, name string, category string, price float64, stock int32) (int64, error) {
	if r.execStmt == nil { var err error; r.execStmt, err = r.db.PrepareContext(ctx, insertAndReturnIDConstMySQL); if err != nil { return 0, err } }
	if r.queryStmt == nil { var err error; r.queryStmt, err = r.db.PrepareContext(ctx, insertAndReturnIDSelectConstMySQL); if err != nil { return 0, err } }
	if _, err := r.execStmt.ExecContext(ctx, name, category, price, stock); err != nil { return 0, err }
	var id int64
	row := r.queryStmt.QueryRowContext(ctx)
	if err := row.Scan(&id); err != nil { return 0, err }
	return id, nil
}

func (r *insertAndReturnIDMySQL) close() error {
	if r.execStmt != nil { if err := r.execStmt.Close(); err != nil { return err } }
	if r.queryStmt != nil { if err := r.queryStmt.Close(); err != nil { return err } }
	return nil
}
func (r *insertAndReturnIDMySQL) withTx(tx *sql.Tx) insertAndReturnIDRunner {
	return &insertAndReturnIDMySQL{execStmt: tx.Stmt(r.execStmt), queryStmt: tx.Stmt(r.queryStmt)}
}

const updateItemConstMySQL = `UPDATE items SET name = ?, price = ?, updated_at = now() WHERE id = ?`

type updateItemMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *updateItemMySQL) exec(ctx context.Context, name string, price float64, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, updateItemConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, price, id)
}

func (r *updateItemMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *updateItemMySQL) withTx(tx *sql.Tx) updateItemRunner { return &updateItemMySQL{stmt: tx.Stmt(r.stmt)} }

const deleteItemConstMySQL = `DELETE FROM items WHERE id = ?`

type deleteItemMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemMySQL) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemMySQL) withTx(tx *sql.Tx) deleteItemRunner { return &deleteItemMySQL{stmt: tx.Stmt(r.stmt)} }

const deleteItemRowsConstMySQL = `DELETE FROM items WHERE id = ?`

type deleteItemRowsMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *deleteItemRowsMySQL) exec(ctx context.Context, id int64) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, deleteItemRowsConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, id)
}

func (r *deleteItemRowsMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *deleteItemRowsMySQL) withTx(tx *sql.Tx) deleteItemRowsRunner { return &deleteItemRowsMySQL{stmt: tx.Stmt(r.stmt)} }

const upsertItemConstMySQL = `INSERT INTO items (name, category, price, stock) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE category = VALUES(category), price = VALUES(price), stock = VALUES(stock)`

type upsertItemMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertItemMySQL) exec(ctx context.Context, name string, category string, price float64, stock int32) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertItemConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category, price, stock)
}

func (r *upsertItemMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertItemMySQL) withTx(tx *sql.Tx) upsertItemRunner { return &upsertItemMySQL{stmt: tx.Stmt(r.stmt)} }

const upsertIgnoreConstMySQL = `INSERT IGNORE INTO items (name, category, price, stock) VALUES (?, ?, 0, 0)`

type upsertIgnoreMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *upsertIgnoreMySQL) exec(ctx context.Context, name string, category string) (sql.Result, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, upsertIgnoreConstMySQL); if err != nil { return nil, err } }
	return r.stmt.ExecContext(ctx, name, category)
}

func (r *upsertIgnoreMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *upsertIgnoreMySQL) withTx(tx *sql.Tx) upsertIgnoreRunner { return &upsertIgnoreMySQL{stmt: tx.Stmt(r.stmt)} }

const searchByNameConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE LOWER(name) LIKE LOWER(?) ORDER BY id`

type searchByNameMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchByNameMySQL) query(ctx context.Context, keyword string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchByNameConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword)
}

func (r *searchByNameMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchByNameMySQL) withTx(tx *sql.Tx) searchByNameRunner { return &searchByNameMySQL{stmt: tx.Stmt(r.stmt)} }

const searchOptionalConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (LOWER(name) LIKE LOWER(?) OR ? IS NULL) ORDER BY id`

type searchOptionalMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *searchOptionalMySQL) query(ctx context.Context, keyword *string, keyword_1 *string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, searchOptionalConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, keyword, keyword_1)
}

func (r *searchOptionalMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *searchOptionalMySQL) withTx(tx *sql.Tx) searchOptionalRunner { return &searchOptionalMySQL{stmt: tx.Stmt(r.stmt)} }

const countByCategoryConstMySQL = `SELECT category, count(*) FROM items GROUP BY category HAVING count(*) >= 0 ORDER BY category`

type countByCategoryMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countByCategoryMySQL) query(ctx context.Context) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countByCategoryConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx)
}

func (r *countByCategoryMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countByCategoryMySQL) withTx(tx *sql.Tx) countByCategoryRunner { return &countByCategoryMySQL{stmt: tx.Stmt(r.stmt)} }

const existsByNameConstMySQL = `SELECT EXISTS (SELECT 1 FROM items WHERE name = ?)`

type existsByNameMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *existsByNameMySQL) query(ctx context.Context, name string) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, existsByNameConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, name), nil
}

func (r *existsByNameMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *existsByNameMySQL) withTx(tx *sql.Tx) existsByNameRunner { return &existsByNameMySQL{stmt: tx.Stmt(r.stmt)} }

const findByFiltersConstMySQL = `SELECT id, name, category, price, stock, is_active, created_at, updated_at FROM items WHERE (((category = ? OR ? IS NULL) AND (price >= ? OR ? IS NULL)) AND (is_active = ? OR ? IS NULL)) ORDER BY id`

type findByFiltersMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findByFiltersMySQL) query(ctx context.Context, category *string, category_1 *string, min_price *float64, min_price_1 *float64, is_active *bool, is_active_1 *bool) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findByFiltersConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category, category_1, min_price, min_price_1, is_active, is_active_1)
}

func (r *findByFiltersMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findByFiltersMySQL) withTx(tx *sql.Tx) findByFiltersRunner { return &findByFiltersMySQL{stmt: tx.Stmt(r.stmt)} }

const countAllConstMySQL = `SELECT count(*) FROM items`

type countAllMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *countAllMySQL) query(ctx context.Context) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, countAllConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx), nil
}

func (r *countAllMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *countAllMySQL) withTx(tx *sql.Tx) countAllRunner { return &countAllMySQL{stmt: tx.Stmt(r.stmt)} }

const listNamesConstMySQL = `SELECT name FROM items WHERE category = ? ORDER BY name`

type listNamesMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listNamesMySQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listNamesConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listNamesMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listNamesMySQL) withTx(tx *sql.Tx) listNamesRunner { return &listNamesMySQL{stmt: tx.Stmt(r.stmt)} }

const listBriefConstMySQL = `SELECT id, name, category FROM items WHERE category = ? ORDER BY id`

type listBriefMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *listBriefMySQL) query(ctx context.Context, category string) (*sql.Rows, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, listBriefConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryContext(ctx, category)
}

func (r *listBriefMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *listBriefMySQL) withTx(tx *sql.Tx) listBriefRunner { return &listBriefMySQL{stmt: tx.Stmt(r.stmt)} }

const findWithExtraConstMySQL = `SELECT id, name, category, price, stock, created_at FROM items WHERE id = ?`

type findWithExtraMySQL struct {
	stmt *sql.Stmt
	db   *sql.DB
}

func (r *findWithExtraMySQL) query(ctx context.Context, id int64) (*sql.Row, error) {
	if r.stmt == nil { var err error; r.stmt, err = r.db.PrepareContext(ctx, findWithExtraConstMySQL); if err != nil { return nil, err } }
	return r.stmt.QueryRowContext(ctx, id), nil
}

func (r *findWithExtraMySQL) close() error { if r.stmt != nil { return r.stmt.Close() }; return nil }
func (r *findWithExtraMySQL) withTx(tx *sql.Tx) findWithExtraRunner { return &findWithExtraMySQL{stmt: tx.Stmt(r.stmt)} }


type itemsRunnerFactoryMySQL struct {}


func (f *itemsRunnerFactoryMySQL) newFindByID(db *sql.DB) findByIDRunner { return &findByIDMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newFindAll(db *sql.DB) findAllRunner { return &findAllMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newFindByCategory(db *sql.DB) findByCategoryRunner { return &findByCategoryMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newListPaged(db *sql.DB) listPagedRunner { return &listPagedMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newInsertItem(db *sql.DB) insertItemRunner { return &insertItemMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newInsertItemRows(db *sql.DB) insertItemRowsRunner { return &insertItemRowsMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newInsertAndReturnID(db *sql.DB) insertAndReturnIDRunner { return &insertAndReturnIDMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newUpdateItem(db *sql.DB) updateItemRunner { return &updateItemMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newDeleteItem(db *sql.DB) deleteItemRunner { return &deleteItemMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newDeleteItemRows(db *sql.DB) deleteItemRowsRunner { return &deleteItemRowsMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newUpsertItem(db *sql.DB) upsertItemRunner { return &upsertItemMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newUpsertIgnore(db *sql.DB) upsertIgnoreRunner { return &upsertIgnoreMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newSearchByName(db *sql.DB) searchByNameRunner { return &searchByNameMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newSearchOptional(db *sql.DB) searchOptionalRunner { return &searchOptionalMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newCountByCategory(db *sql.DB) countByCategoryRunner { return &countByCategoryMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newExistsByName(db *sql.DB) existsByNameRunner { return &existsByNameMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newFindByFilters(db *sql.DB) findByFiltersRunner { return &findByFiltersMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newCountAll(db *sql.DB) countAllRunner { return &countAllMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newListNames(db *sql.DB) listNamesRunner { return &listNamesMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newListBrief(db *sql.DB) listBriefRunner { return &listBriefMySQL{db: db} }

func (f *itemsRunnerFactoryMySQL) newFindWithExtra(db *sql.DB) findWithExtraRunner { return &findWithExtraMySQL{db: db} }


