// Code generated by sqlgen; DO NOT EDIT.
package integration

import (
	"time"
)

type CatCount struct {
	Category string `json:"category"`
	Cnt int64 `json:"cnt"`
}

type ExistsByName struct {
	Exists bool `json:"exists"`
}

type Item struct {
	ID int64 `json:"id"`
	Name string `json:"name"`
	Category string `json:"category"`
	Price float64 `json:"price"`
	Stock int32 `json:"stock"`
	IsActive bool `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ItemBrief struct {
	ID int64 `json:"id"`
	Name string `json:"name"`
	Category string `json:"category"`
}

